blackoxfarm/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # App URL's
    path("", include("website.urls", namespace="website"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path 
from website import views 
from website.views import (
    Blog,
    Blogdetail,
)

app_name = 'website'
urlpatterns = [
    path("icd", views.indcnt, name=""),
    path("", views.landing, name='landing'),
    path("Farm-operations/", views.farmoperations, name="farmoperations"),
    path("farmoperation/<int:pk>/", views.farmoperationdetail, name="operationdetail"),
    path("About-BlackOX/", views.aboutfarm, name="about"),
    path("Contact-BlackOX/", views.contact, name="contact"),
    path("Careers/", views.careers, name="careers"),
    path("job-post/<int:pk>/", views.careerdetail, name="careerdetail"),
    path("apply-to-post/<int:pk>/", views.applytopost, name="applytopost"),
    path("FAQs/", views.FAQ, name="faqs"),
    path("ourfarms/", views.ourfarms, name="ourfarms"),
    path("news-feed/", Blog.as_view(), name="blog"),
    path("article/<int:pk>", Blogdetail.as_view(), name="article-detail"),
]

website/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
# Create your models here.

class Breed(models.Model):
    breed_name = models.CharField(max_length=500, blank=True, null=True)
    description_of_breed = models.TextField(blank=True)

    def __str__(self):
        return f"Breed: {self.breed_name}"
    
class Cattle(models.Model):
    breed_type = models.ForeignKey(Breed, on_delete=models.CASCADE, blank=True)
    Age = models.IntegerField(blank=True)
    image = models.ImageField(upload_to="cattles/")
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True)
    date_uploaded = models.DateTimeField(auto_now_add=True)
    stock = models.BooleanField(default=False)

    class Meta:
        ordering = ['-Age']

    def __str__(self):
        return f"Cattle: {self.name}; Breed Type: {self.breed_type.breed_name}"
    
class Sheep(models.Model):
    breed_type = models.ForeignKey(Breed, on_delete=models.CASCADE, blank=True)
    Age = models.IntegerField(blank=True)
    image = models.ImageField(upload_to="sheep/")
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True)
    date_uploaded = models.DateTimeField(auto_now_add=True)
    stock = models.BooleanField(default=False)

    class Meta:
        ordering = ['-Age']

    def __str__(self):
        return f"Sheep: {self.name}; Breed Type: {self.breed_type.breed_name}"
    
class Contact(models.Model):
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    message = models.TextField(blank=True)
    email = models.EmailField(blank=True)
    tel = models.CharField(max_length=13, blank=True, null=True, verbose_name="Telephone Number")

    def __str__(self):
        return f"Contact Message From: {self.first_name} {self.last_name}"
    
# Blog Model 
class Post(models.Model):
    title = models.CharField(max_length=255)
    hearder_image = models.ImageField(null=True, blank=True, upload_to="images/")
    title_tag = models.CharField(max_length=255)
    body = models.TextField(blank=True, null=True)
    post_date = models.DateField(auto_now_add=True)
    post_time = models.DateTimeField(auto_now_add=True)
    Category =  models.CharField( max_length=50)
    Snippet =  models.CharField( max_length=50)
    
    
    def __str__(self):
        return self.title + ' | ' 

    def get_absolute_url(self):
        return reverse("website:article-detail", kwargs={"pk": self.pk})
    
# Career Model/ 
class JobPost(models.Model):
    """
    Job Opening model fields may be
    adjusted for optional modeling
    """
    title = models.CharField(max_length=300, blank=True, null=True)
    closing_date = models.DateField(editable=True, blank=True)
    number_of_open_position = models.IntegerField(blank=True)
    description = models.TextField(blank=True)
    
    def __str__(self):
        return self.title
    
class FarmOperation(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    details = models.TextField(blank=True)
    image1 = models.ImageField(upload_to="operations/", blank=True)
    image2 = models.ImageField(upload_to="operations/", blank=True)

    def __str__(self):
        return self.name
    
class JobApplicant(models.Model):
    fullname = models.CharField(max_length=800, blank=True, null=True)
    phonenumber = models.CharField(max_length=13, blank=True, null=True)
    email = models.EmailField(blank=True)
    resume = models.FileField(blank=True, upload_to="resumes/")
    motivational_letter = models.TextField(blank=True)

    def __str__(self):
        return self.fullname

website/views.py
from django.urls import reverse 
from django.shortcuts import render, redirect
from website.models import (
    Cattle,
    Contact,
    Post,
    JobPost,
    FarmOperation
)
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
import datetime
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
# Create your views here.

def indcnt(request):
    post = Post.objects.all()
    operations = FarmOperation.objects.all()
    return render(request, "website/index.html", {
        "posts": post,
        "operations": operations
    })

def landing(request):
    operations = FarmOperation.objects.all()
    # Pass Data into the context dictionary
    context = {
        'operations':operations
    }
    return render(request, "website/landing.html", context)

def ourfarms(request):
    operations = FarmOperation.objects.all()
    return render(request, "website/ourfarms.html", {
        "operations": operations
    })

def farmoperations(request):
    operations = FarmOperation.objects.all()
    return render(request, "website/farmsoperations.html", {
        "operations": operations
    })

def farmoperationdetail(request, pk):
    operation = FarmOperation.objects.get(pk=pk)
    operations = FarmOperation.objects.all()
    return render(request, "website/operationdetail.html", {
        "operation": operation,
        "operations": operations
    })

def aboutfarm(request):
    operations = FarmOperation.objects.all()
    return render(request, "website/about.html", {
        "operations": operations
    })

def contact(request):
    if request.method == "GET":
        operations = FarmOperation.objects.all()
        return render(request, "website/contact.html", {
            "operations": operations
        })
    
    if request.method == "POST":
        firstname = request.POST.get("firstname")
        lastname = request.POST.get("lastname")
        phonenumber = request.POST.get("phonenumber")
        email = request.POST.get("email")
        message = request.POST.get("message")

        if not email:
            messages.error(request, "Email is required to proceed")
            return redirect(reverse("website:contact"))
        
        try:
            c = Contact.objects.create(
                first_name = firstname,
                last_name = lastname,
                message = message,
                email = email,
                tel= phonenumber
            )

            send_mail(
                "Thank you for contacting us.",
                "This is an automated notifier. Our Team will be intouch with you shortly",
                "test@com.com",
                [email],
                fail_silently=True
            )

            messages.success(request, "Thank you for your request")

            return redirect(reverse("website:contact"))
        except BadHeaderError as b:
            messages.error(request, f"{b}")

            return redirect("website:contact")
            

def careers(request):
    posts = JobPost.objects.all()
    operations = FarmOperation.objects.all()
    return render(request, "website/careers.html", {
        'posts':posts,
        "operations": operations
        })

def careerdetail(request, pk):
    post = JobPost.objects.get(pk=pk)
    operations = FarmOperation.objects.all()
    return render(request, "website/careerdetail.html", {
        "post": post,
        "operations": operations
    })

def applytopost(request, pk):
    if request.method == "GET":
        operations = FarmOperation.objects.all()
        post = JobPost.objects.get(pk=pk)
        return render(request, "website/applytopost.html", {
            "post":post,
            "operations": operations
        })
    
    if request.method == "POST":
        pass
    
def FAQ(request):
    operations = FarmOperation.objects.all()
    return render(request, "website/faq.html", {
        "operations": operations
    })

# blog class based views
class Blog(ListView):
    model = Post
    template_name = 'website/blog-home-2.html'
    ordering = ['-post_time']

    def get_context_data(self, **kwargs):
        # headerpost = Post.objects.get()
        now = datetime.datetime.today()
        print(now)
        headerpost = Post.objects.all()[:1]
        operations = FarmOperation.objects.all()
        context = super().get_context_data(**kwargs)
        context["header"] = headerpost
        context["operations"] = operations
        return context

class Blogdetail(DetailView):
    model = Post
    template_name = 'website/blog-post.html'

    def get_context_data(self, **kwargs):
        data = get_object_or_404(Post, id=self.kwargs['pk'])
        recentposts = Post.objects.all().order_by('-post_time').exclude(pk=data.pk)[:3]
        operations = FarmOperation.objects.all()
        print(recentposts)
        context = super().get_context_data(**kwargs)
        context["recentposts"] = recentposts
        context["operations"] = operations
        return context

templates/website/applytopost.html
{% extends "website/index.html" %}
{% load static %}

{% block title %}{{post.title}}{% endblock title %}

{% block header %}
	<!-- full Title -->
	<div class="full-title" style="background: url({% static "website/images/c3c728cd-d543-428c-881d-f26a2b34a48b.png" %}) no-repeat center;">
		<div class="container">
			<!-- Page Heading/Breadcrumbs -->
			<h1 class="mt-4 mb-3">Apply to Post
				<small>Farming for Stability</small>
			</h1>
		</div>
	</div>
{% endblock header %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
		<div class="breadcrumb-main">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="{% url "website:landing" %}">Home</a>
				</li>
                <li class="breadcrumb-item">
					<a href="{% url "website:careers" %}">Careers</a>
				</li>
                <li class="breadcrumb-item">
					<a href="{% url "website:careerdetail" post.pk %}">Job Opening</a>
				</li>
				<li class="breadcrumb-item active">Apply to post</li>
			</ol>
		</div>

      <!-- Content Row -->
      <div class="row">
        <!-- Map Column -->
        <div class="col-lg-8 mb-4">
          <!-- Embedded Google Map -->
          <h3>Apply To Post</h3>
        </div>
        <!-- Contact Details Column -->
        <div class="col-lg-4 mb-4 contact-right">
          <h3>{{post.title}}</h3>
          
          <p>
            <abbr title="Phone">Rates</abbr>: R/
          </p>
          <p>
            <abbr title="Email">Occupation Time</abbr>:NaN
            
          </p>
          <p>
            <abbr title="Hours">Requirements</abbr>: NaN
          </p>
        </div>
      </div>
      <!-- /.row -->

      <!-- Contact Form -->
      <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
      <div class="row">
        <div class="col-lg-8 mb-4 contact-left">
          <h3>Job Opening</h3>
          <form name="sentMessage" id="contactForm" novalidate>
            <div class="control-group form-group">
              <div class="controls">
                <label>Full Name:</label>
                <input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">
                <p class="help-block"></p>
              </div>
            </div>
            <div class="control-group form-group">
              <div class="controls">
                <label>Phone Number:</label>
                <input type="tel" class="form-control" id="phone" required data-validation-required-message="Please enter your phone number.">
              </div>
            </div>
            <div class="control-group form-group">
              <div class="controls">
                <label>Email Address:</label>
                <input type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
              </div>
            </div>
            <div class="control-group form-group">
                <div class="controls">
                  <label>Upload Resume:</label>
                  <input type="file" class="form-control" required data-validation-required-message="Upload Resume..">
                </div>
              </div>
            <div class="control-group form-group">
              <div class="controls">
                <label>Additional Motive:</label>
                <textarea rows="5" cols="100" class="form-control" id="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
              </div>
            </div>
            <div id="success"></div>
            <!-- For success/fail messages -->
            <button type="submit" class="btn btn-primary" id="sendMessageButton">Send Message</button>
          </form>
        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->
{% endblock content %}

templates/website/blog-post.html
{% extends "website/index.html" %}
{% load static %}

{% block title %}{{post.title}}{% endblock title %}

{% block header %}
	<!-- full Title -->
	<div class="full-title" style="background: url({{post.hearder_image.url}}) no-repeat center;">
		<div class="container">
			<!-- Page Heading/Breadcrumbs -->
			<h1 class="mt-4 mb-3">{{post.title}}
				<small>{{post.Snippet}}</small>
			</h1>
		</div>
	</div>
{% endblock header %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
		<div class="breadcrumb-main">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="{% url "website:landing" %}">Home</a>
				</li>
        <li class="breadcrumb-item">
					<a href="{% url "website:blog" %}">News Feed</a>
				</li>
				<li class="breadcrumb-item active">{{post.title}}</li>
			</ol>
		</div>

		<div class="row">
        <!-- Post Content Column -->
			<div class="col-lg-8">

				<!-- Preview Image -->
				<img class="img-fluid rounded" src="{{post.hearder_image.url}}" alt="{{post.title}}" />
				<hr>
					<!-- Date/Time -->
					<p>Posted on {{post.post_time}}</p>
				<hr>
				<!-- Post Content -->
				<p class="lead">{{post.Snippet}}</p>
				<p>{{post.body}}</p>

			<hr>

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4 blog-right-side">

          <!-- Search Widget -->
          <div class="card mb-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Web Design</a>
                    </li>
                    <li>
                      <a href="#">HTML</a>
                    </li>
                    <li>
                      <a href="#">Freebies</a>
                    </li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">JavaScript</a>
                    </li>
                    <li>
                      <a href="#">CSS</a>
                    </li>
                    <li>
                      <a href="#">Tutorials</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->
{% endblock content %}

templates/website/careerdetail.html
{% extends "website/index.html" %}
{% load static %}

{% block title %}{{post.title}}{% endblock title %}

{% block header %}
	<!-- full Title -->
	<div class="full-title" style="background: url({% static "website/images/c3c728cd-d543-428c-881d-f26a2b34a48b.png" %}) no-repeat center;">
		<div class="container">
			<!-- Page Heading/Breadcrumbs -->
			<h1 class="mt-4 mb-3">{{post.title}}
				<small>Our Agri-world</small>
			</h1>
		</div>
	</div>
{% endblock header %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
		<div class="breadcrumb-main">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="{% url "website:landing" %}">Home</a>
				</li>
                <li class="breadcrumb-item">
					<a href="{% url "website:careers" %}">Careers</a>
				</li>
				<li class="breadcrumb-item active">Job Opening</li>
			</ol>
		</div>

		<div class="row">
        <!-- Post Content Column -->
			<div class="col-lg-8">

				<!-- Preview Image -->
				<img class="img-fluid rounded" src="{% static "website/images/c3c728cd-d543-428c-881d-f26a2b34a48b.png" %}" alt="" />
				<hr>
					<!-- Date/Time -->
					<p>Closing Date: {{post.closing_date}}</p>
				<hr>
				<!-- Post Content -->
				<p class="lead">Vacancies: {{post.number_of_open_position}}. Closing Date: {{post.closing_date}}</p>
				
				<p>{{post.description}}</p>

			<hr>
        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4 blog-right-side">

          <!-- Search Widget -->
          <div class="card mb-4">
            <h5 class="card-header">Apply</h5>
            <div class="card-body">
              <div class="input-group">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button"><a href="{% url "website:applytopost" post.pk %}">Apply</a></button>
                </span>
              </div>
            </div>
          </div>
        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->
{% endblock content %}

templates/website/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>{% block title %}BlackOx Farm{% endblock title %}</title>
	<!-- Bootstrap core CSS -->
	<link href="{% static "website/vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
	<!-- Fontawesome CSS -->
	<link href="{% static "website/css/all.css" %}" rel="stylesheet">
	<!-- Custom styles for this template -->
	<link href="{% static "website/css/style.css" %}" rel="stylesheet">
</head>
<body onload="myFunction();">
   <div id="loader">
      <div class="sk-circle">
         <div class="sk-circle1 sk-child"></div>
         <div class="sk-circle2 sk-child"></div>
         <div class="sk-circle3 sk-child"></div>
         <div class="sk-circle4 sk-child"></div>
         <div class="sk-circle5 sk-child"></div>
         <div class="sk-circle6 sk-child"></div>
         <div class="sk-circle7 sk-child"></div>
         <div class="sk-circle8 sk-child"></div>
         <div class="sk-circle9 sk-child"></div>
         <div class="sk-circle10 sk-child"></div>
         <div class="sk-circle11 sk-child"></div>
         <div class="sk-circle12 sk-child"></div>
      </div>
   </div>

   <section id="doc" style="display:none;">
    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-light top-nav fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url "website:landing" %}">
            <img src="{% static "website/images/c3c728cd-d543-428c-881d-f26a2b34a48b.png"%}" alt="Blackoxfarm logo" />
            </a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<span class="fas fa-bars"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
               <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                     <a class="nav-link active" href="{% url "website:landing" %}">Home</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url "website:about" %}">About</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url "website:ourfarms" %}">Our Farms</a>
                  </li>
                  <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     Farm Operations
                     </a>
                     <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                        {% for operation in operations %}
                        <a class="dropdown-item" href="{% url "website:operationdetail" operation.pk %}">{{operation.name}}</a>
                        {% endfor %}
                     </div>
                  </li>
                  <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     Site
                     </a>
                     <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                        <a class="dropdown-item" href="{% url "website:careers" %}">Career @ Blaxkox Farm</a>
                        <a class="dropdown-item" href="{% url "website:blog" %}">News Feed</a>
                        <a class="dropdown-item" href="{% url "website:faqs" %}">FAQ</a>
                     </div>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url "website:contact" %}">Contact</a>
                  </li>
               </ul>
            </div>
        </div>
    </nav>
    {% block header %}
    <header class="slider-main">
        <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
            <ol class="carousel-indicators">
               <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
               <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
               <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
               <!-- Slide One - Set the background image for this slide in the line below -->
               <div class="carousel-item active" style="background-image: url({% static 'website/images/IMG-20230924-WA0017.jpg'%});">
                  <div class="carousel-caption d-none d-md-block">
                     <h3 class="anime3">Stud Sires</h3>
                     <p >Our Breeding bulls</p>
                  </div>
               </div>
               <!-- Slide Two - Set the background image for this slide in the line below -->
               <div class="carousel-item" style="background-image: url({% static 'website/images/IMG-20230924-WA0018.jpg'%});">
                  <div class="carousel-caption d-none d-md-block">
                     <h3 class="anime3">Boran Cattles</h3>
                     <p >Our finest quality of Cattles</p>
                  </div>
               </div>
               <!-- Slide Three - Set the background image for this slide in the line below -->
               <div class="carousel-item" style="background-image: url({% static 'website/images/IMG-20230924-WA0019.jpg'%});">
                  <div class="carousel-caption d-none d-md-block">
                     <h3 class="anime3">Dorper Sheeps</h3>
                     <p >Our range of sheep breed</p>
                  </div>
               </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
            </a>
        </div>
    </header>
    {% endblock header %}

    {% block content %}
    
    {% endblock content %}
    <!--footer starts from here-->
    <footer class="footer">
        <div class="container bottom_border">
            <div class="row">
               <div class="col-lg-3 col-md-6 col-sm-6 col">
					<h5 class="headin5_amrc col_white_amrc pt2">Find us</h5>
					<!--headin5_amrc-->
					<p class="mb10">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
					<p><i class="fa fa-location-arrow"></i> 9878/25 sec 9 rohini 35 </p>
					<p><i class="fa fa-phone"></i> +91-9999878398 </p>
					<p><i class="fa fa fa-envelope"></i> info@example.com </p>
               </div>				
					<!--footer_ul2_amrc ends here-->
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<h5 class="headin5_amrc col_white_amrc pt2">Quick Links</h5>
					<!--headin5_amrc-->
					<ul class="footer_ul_amrc">
						<li><a href="{% url "website:careers" %}">Career @ BlackOx Farms</a></li>
						<li><a href="{% url "website:blog" %}">News Feed</a></li>
						<li><a href="{% url "website:faqs" %}">FAQs</a></li>
						<li><a href="{% url "website:about" %}">About Us</a></li>
						<li><a href="{% url "website:farmoperations" %}">Our Services</a></li>
						<li><a href="{% url "website:contact" %}">Get In Touch</a></li>
					</ul>
					<!--footer_ul_amrc ends here-->
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6 ">
					<h5 class="headin5_amrc col_white_amrc pt2">Recent posts</h5>
					<!--headin5_amrc-->
					<ul class="footer_ul_amrc">
            
                  {% for post in posts %}
						<li class="media">
							<div class="media-left">
								<img class="img-fluid" src="{{post.hearder_image.url}}" alt="{{post.title}}" />
							</div>
							<div class="media-body">
								<p>{{post.title}}</p>
								<span>{{post.post_date}}</span>
							</div>
						</li>
						{% endfor %}
                 
					</ul>
					<!--footer_ul_amrc ends here-->
				</div>
			</div>
		</div>
        <div class="container">
            <div class="footer-logo">
				<a href="{% url "website:landing" %}"><img src="{% static "website/images/c3c728cd-d543-428c-881d-f26a2b34a48b.png"%}" alt="Blackox farms logo" /></a>
			</div>
            <!--foote_bottom_ul_amrc ends here-->
            <p class="copyright text-center">All Rights Reserved. &copy; 2024 <a href="#">BlackOx Farms</a> Design By : 
				<a href="https://www.genincebronx.co.za/">G|B Genince Bronx</a>
            </p>
            <ul class="social_footer_ul">
				<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
				<li><a href="#"><i class="fab fa-twitter"></i></a></li>
				<li><a href="#"><i class="fab fa-linkedin"></i></a></li>
				<li><a href="#"><i class="fab fa-instagram"></i></a></li>
            </ul>
            <!--social_footer_ul ends here-->
        </div>
    </footer>
	</section>  

   <!-- Bootstrap core JavaScript -->
   <script src="{% static "website/vendor/jquery/jquery.min.js"%}"></script>
   <script src="{% static "website/vendor/bootstrap/js/bootstrap.bundle.min.js"%}"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
   <script src="{% static "website/js/textAnime.js" %}"></script>
   <script src="{% static "website/js/loader.js" %}"></script>
</body>
</html>